name: pull request example

on: 
  workflow_dispatch

jobs:
  pull-request:
    runs-on: ubuntu-latest
    defaults: 
      run:
        working-directory: typescript-project
    steps:
      - name: checkout 
        uses: actions/checkout@v2

      - name: setup node
        uses: actions/setup-node@v2
        with:
          node-version: "16.x"
          cache: "npm"

      - name: install yarn   
        run: yarn install --frozen-lockfile

      - name: run linting
        run: yarn lint

      - name: build
        run: yarn build

      - name: run tests
        run: yarn test

  
